### PR TITLE
modify to be a valid package

### PR DESCRIPTION
**Pull request by marrlex**
Please merge this and update version numbering.
The `src` directory is moved into `lib` directory, and modify `lib/src/synthesizer.dart` not to use flutter package (to keep it pure dart).
If there are multiple necessary imports, you can export them from single file.

### CODE REVIEW

**Comment by chipweinberger** [comment]
Thanks for your contribution.

 Some of these changes have already been taken. Can you rebase?

**Comment by chipweinberger** [comment]
also please update changelog and pubspec.yaml

**Comment by marrlex** [comment]
I worked from your latest main branch.
Looking at the history, it is probably incompletely committed. I  confirm that you have moved the directory on your repository.

I think I should not be involved in the change log or version. Because I don't know which to merge and how.
Would you please edit them yourself?

**Comment by chipweinberger** [comment]
indeed. just pushed.

**Pull request closed without merging**
